@startuml
actor "Toby (Tester)" as toby
participant "CLI tool" as cli
participant "Environment" as env
participant "Runs Service" as runsService

toby-> cli: runs submit
        activate cli
        cli-> env: read GALASA_BEARER_TOKEN

        cli->   runsService : post(runs,bearer-token) 
                activate runsService
                runsService-> Dex : Is this bearer token valid ?
                runsService <--Dex:OK

note over runsService
The test runs can now go ahead.
end note
        cli<--  runsService:OK
                deactivate runsService


toby<-- cli: OK
        deactivate cli
@enduml