@startuml

actor "Toby (Tester)" as toby
participant "Galasa Web UI" as webUI
participant Dex as Dex
database "Configured Users DB" as db

toby -> webUI: Get request
toby<-- webUI: Logon challenge 
toby -> webUI: User id and password
    webUI -> Dex: "Authentication request (user login)"
        Dex -> db : Authentication request
        Dex<-- db :  User is valid Response
    webUI<--Dex: OK
toby<-- webUI: main web app UI
@enduml