#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#


apiVersion: galasa.dev/v1alpha
kind: Release
metadata:
  name: galasa-release


release:
  version: 0.39.0

# Dependencies with bom: true need their versions stated explicitly
# As the galasa-bom is a component consumed by users, its too risky
# to have the platform provide the versions.

external:
  bundles:
  - group: com.google.code.gson
    artifact: gson
    version: 2.10.1
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: com.sun.xml.bind
    artifact: jaxb-osgi
    obr: true
    # Added since Isolated selects bundles based on this line,
    # and not just all bundles appearing in this file,
    # but might not be needed in Isolated.
    isolated: true

  - group: commons-codec
    artifact: commons-codec
    version: 1.16.1
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: commons-collections
    artifact: commons-collections
    obr: true
    mvp: true
    isolated: true

  - group: commons-io
    artifact: commons-io
    version: 2.16.1
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: commons-lang
    artifact: commons-lang
    obr: true
    mvp: true
    isolated: true

  # commons-logging is not included in the OBR because it is exported in
  # the log4j2.bridge bundle and that bundle is directly installed into 
  # the Felix framework at runtime.
  # Adding it into the OBR causes run logs to no longer be captured correctly!
  - group: commons-logging
    artifact: commons-logging
    version: 1.3.4
    obr: false
    bom: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.com.jcraft.jsch
    obr: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.com.auth0.jwt
    obr: true
    mvp: false      # Only used for Authentication - not needed.
    isolated: false # Only used for Authentication - not needed.

  - group: dev.galasa
    artifact: dev.galasa.wrapping.gson
    version: 0.39.0
    obr: true
    bom: true
    mvp: true
    isolated: true

  - artifact: dev.galasa.wrapping.httpclient-osgi
    version: 0.39.0
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.io.grpc.java
    obr: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.io.kubernetes.client-java
    obr: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.protobuf-java
    obr: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.jta
    obr: true
    mvp: true
    isolated: true

  - artifact: dev.galasa.wrapping.velocity-engine-core
    obr: true
    mvp: true
    isolated: true

  - group: dev.galasa
    artifact: dev.galasa.wrapping.kafka.clients
    obr: true
    mvp: false      # Only used in Kafka extension - not needed.
    isolated: false # Only used in Kafka extension - not needed.

  - group: io.prometheus
    artifact: simpleclient
    obr: true
    mvp: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_common
    obr: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_hotspot
    obr: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_httpserver
    obr: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_tracer_common
    obr: true
    mvp: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_tracer_otel
    obr: true
    mvp: true
    isolated: true

  - group: io.prometheus
    artifact: simpleclient_tracer_otel_agent
    obr: true
    mvp: true
    isolated: true

  - group: jakarta.activation
    artifact: jakarta.activation-api
    obr: true
    mvp: true
    isolated: true

  - group: jakarta.xml.bind
    artifact: jakarta.xml.bind-api
    obr: true
    mvp: true
    isolated: true

  - group: javax.validation
    artifact: validation-api
    version: 2.0.1.Final
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: org.apache.bcel
    artifact: bcel
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.commons
    artifact: commons-collections4
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.commons
    artifact: commons-compress
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.commons
    artifact: commons-lang3
    version: 3.17.0
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: org.apache.derby
    artifact: derbyclient
    obr: true
    mvp: false      # Added into MVP through pom2.xml
    isolated: false # Added into Isolated through pom2.xml

  - group: org.apache.felix
    artifact: org.apache.felix.configadmin
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.fileinstall
    obr: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.gogo.command
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.gogo.runtime
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.gogo.shell
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.http.jetty
    obr: true
    isolated: true

  - group: org.apache.felix
    artifact: org.apache.felix.http.servlet-api
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.httpcomponents
    artifact: httpclient
    mvp: true
    isolated: true

  - group: org.apache.httpcomponents
    artifact: httpcore-osgi
    version: 4.4.14
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: org.apache.httpcomponents
    artifact: httpcore
    mvp: true
    isolated: true

  - group: org.apache.httpcomponents
    artifact: httpmime
    mvp: true
    isolated: true

  - group: org.apache.logging.log4j
    artifact: log4j-api
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.logging.log4j
    artifact: log4j-core
    obr: true
    mvp: true
    isolated: true

  - group: org.apache.logging.log4j
    artifact: log4j-slf4j-impl
    obr: true
    mvp: true
    isolated: true

  - group: org.assertj
    artifact: assertj-core
    version: 3.11.1
    obr: true
    bom: true
    mvp: true
    isolated: true

  - group: org.bouncycastle
    artifact: bcpkix-jdk18on
    obr: true
    mvp: false      # Only used for Docker controller - not needed.
    isolated: false # Only used for Docker controller - not needed.

  - group: org.bouncycastle
    artifact: bcprov-jdk18on
    obr: true
    mvp: false      # Only used for Docker controller - not needed.
    isolated: false # Only used for Docker controller - not needed.

  - group: org.bouncycastle
    artifact: bcutil-jdk18on
    obr: true
    mvp: false      # Only used for Docker controller - not needed.
    isolated: false # Only used for Docker controller - not needed.

  - group: org.osgi
    artifact: org.osgi.service.component.annotations
    version: 1.3.0
    bom: true
    mvp: true
    # Added since Isolated selects bundles based on this line,
    # and not just all bundles appearing in this file,
    # but might not be needed in Isolated.
    isolated: true

  - group: org.slf4j
    artifact: slf4j-api
    version: 1.7.36
    obr: true
    mvp: true
    isolated: true

  - group: org.yaml
    artifact: snakeyaml
    obr: true
    mvp: true
    isolated: true
