#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Build from Managers

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths: ['modules/managers/**']

env:
  REGISTRY: ghcr.io
  NAMESPACE: galasa-dev
  BRANCH: ${{ github.ref_name }}

jobs:

  build-managers:
    name: Build the 'managers' module of Galasa
    uses: ./.github/workflows/managers.yaml
    secrets: inherit

  build-obr:
    name: Build the 'obr' module of Galasa
    needs: [build-managers]
    uses: ./.github/workflows/obr.yaml
    secrets: inherit
