#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Build from Buildutils

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['modules/buildutils/**']

env:
  REGISTRY: ghcr.io
  NAMESPACE: galasa-dev
  BRANCH: ${{ github.ref_name }}

jobs:

  build-buildutils:
    name: Build the 'buildutils' module of Galasa
    uses: ./.github/workflows/buildutils.yaml
    secrets: inherit

  build-framework:
    name: Build the 'framework' module of Galasa
    needs: [build-buildutils]
    uses: ./.github/workflows/build-from-framework.yaml
    secrets: inherit