#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Build from CLI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths: ['modules/cli/**']

env:
  REGISTRY: ghcr.io
  NAMESPACE: galasa-dev
  BRANCH: ${{ github.ref_name }}

jobs:
  
  build-cli:
    name: Build the 'cli' module of Galasa
    uses: ./.github/workflows/cli.yaml
    secrets: inherit