#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Managers main build

on:
  workflow_call:

env:
  BRANCH: ${{ github.ref_name }}

jobs:
  log-github-ref:
    name: Log the GitHub ref this workflow is running on (Branch or tag that received dispatch)
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub ref of workflow
        run: |
          echo "This workflow is running on GitHub ref ${{ env.BRANCH }}"

  build-managers:
    name: Build Managers source code and Docker image for development Maven registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'
          # cache: 'maven'

      - name: Print githash
        run: |
          echo $GITHUB_SHA > ./managers.githash

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      # - name: Restore cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ github.workspace }}/modules/artefacts
      #     key: cache-key-${{ env.BRANCH }}
      #     restore-keys: |
      #       cache-key-

      - name: Build Managers source code
        working-directory: modules/managers
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_signingKeyId:  ${{ secrets.GPG_KEYID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          set -o pipefail
          gradle -b galasa-managers-parent/build.gradle check publishToMavenLocal publish --info \
          --no-daemon --console plain \
          -Dorg.gradle.jvmargs=-Xmx4096M \
          -PsourceMaven=${{ github.workspace }}/modules/artefacts \
          -PcentralMaven=https://repo.maven.apache.org/maven2/ \
          -PtargetMaven=${{ github.workspace }}/modules/artefacts \
          -PjacocoEnabled=true \
          -PisMainOrRelease=true 2>&1 | tee build.log
        
      - name: Upload Gradle Build Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: managers-gradle-build-log
          path: modules/managers/build.log
          retention-days: 7
          
      - name: Upload Jacoco Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/galasa-managers-parent/**/**/build/reports/**/*.html
          retention-days: 7
          if-no-files-found: ignore

      # - name: Save cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ github.workspace }}/modules/artefacts
          # key: cache-key-${{ env.BRANCH }}

      - name: Show contents of cache directory
        run : |
          ls -R ${{ github.workspace }}/modules/artefacts || true