#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Extensions pull request build

on:
  workflow_call:
    inputs:
      changed:
        description: 'True if this module has been changed and should be rebuilt'
        required: true
        type: string

jobs:

  log-unchanged:
    name: Extensions is unchanged
    if: ${{ inputs.changed == 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Log this module is unchanged
        run: |
          echo "The extensions module is unchanged"

  build-extensions:
    name: Build Extensions source code
    if: ${{ inputs.changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'
      
      - name: Print githash
        run: |
          echo $GITHUB_SHA > ./extensions.githash

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
          cache-disabled: true

      - name: Download wrapping artifacts
        uses: actions/download-artifact@v4
        with:
          name: wrapping
          path: modules/artifacts/dev/galasa
          github-token: ${{ github.token }}
          run-id: 11364581065

      - name: Download gradle artifacts
        uses: actions/download-artifact@v4
        with:
          name: gradle
          path: modules/artifacts/dev/galasa
          github-token: ${{ github.token }}
          run-id: 11364581065

      - name: Download maven artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven
          path: modules/artifacts/dev/galasa
          github-token: ${{ github.token }}
          run-id: 11364581065

      - name: Download framework artifacts
        uses: actions/download-artifact@v4
        with:
          name: framework
          path: modules/artifacts/dev/galasa
          github-token: ${{ github.token }}
          run-id: 11364581065

      - name: Build Extensions source code with gradle
        working-directory: modules/extensions
        run: |
          gradle -b galasa-extensions-parent/build.gradle check publish --info \
          --no-daemon --console plain \
          -PsourceMaven=${{ github.workspace }}/modules/artifacts \
          -PcentralMaven=https://repo.maven.apache.org/maven2/ \
          -PtargetMaven=${{ github.workspace }}/modules/extensions/artifacts

      - name: Upload extensions artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extensions
          path: modules/extensions/artifacts/dev/galasa
          retention-days: 7