#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Framework pull request build

on:
  workflow_call:
    inputs:
      changed:
        description: 'True if this module has been changed and should be rebuilt'
        required: true
        type: string
  
jobs:

  log-unchanged:
    name: Framework is unchanged
    if: ${{ inputs.changed == 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Log this module is unchanged
        run: |
          echo "The framework module is unchanged"

  build-framework:
    name: Build Framework using openapi2beans and gradle
    if: ${{ inputs.changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'
      
      - name: Print githash
        run: |
          echo $GITHUB_SHA > ./framework.githash
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
          cache-disabled: true
      
      - name: Build servlet beans with openapi2beans
        env:
          YAML_LOCATION: "modules/framework/galasa-parent/dev.galasa.framework.api.openapi/src/main/resources/openapi.yaml"
          OUTPUT_LOCATION: "modules/framework/galasa-parent/dev.galasa.framework.api.beans/src/main/java"
          PACKAGE: "dev.galasa.framework.api.beans.generated"
        run: |
          docker run --rm -v ${{ github.workspace }}:/var/workspace ghcr.io/galasa-dev/openapi2beans:main generate --yaml var/workspace/${{ env.YAML_LOCATION }} --output var/workspace/${{ env.OUTPUT_LOCATION }} --package ${{ env.PACKAGE }}

      # - name: Get last successful workflow run ID for Main builds
      #   id: get-workflow-id
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run : |
      #     WORKFLOW_ID=$(gh run list --repo jadecarino/galasa --workflow "Main build orchestrator" --status success --limit 1 | grep -v STATUS | cut -d' ' -f6)
      #     echo "::set-output name=workflow_id::${WORKFLOW_ID}"

      - name: Download wrapping artifacts
        uses: actions/download-artifact@v4
        with:
          name: wrapping
          path: modules/artifacts/dev/galasa
          # run-id: ${{ steps.get-workflow-id.outputs.workflow_id }}
          run-id: 11364581065

      - name: Download gradle artifacts
        uses: actions/download-artifact@v4
        with:
          name: gradle
          path: modules/artifacts/dev/galasa
          # run-id: ${{ steps.get-workflow-id.outputs.workflow_id }}
          run-id: 11364581065

      - name: Download maven artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven
          path: modules/artifacts/dev/galasa
          # run-id: ${{ steps.get-workflow-id.outputs.workflow_id }}
          run-id: 11364581065

      - name: Build Framework source code
        working-directory: modules/framework
        run: |
          gradle -b galasa-parent/build.gradle check publish --info \
          --no-daemon --console plain \
          -Dorg.gradle.jvmargs=-Xmx5120M \
          -PsourceMaven=${{ github.workspace }}/modules/artifacts \
          -PcentralMaven=https://repo.maven.apache.org/maven2/ \
          -PtargetMaven=${{ github.workspace }}/modules/framework/artifacts
      
      # - name: Upload Jacoco Reports as artifact
      #   if: failure()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: unit-tests
      #     path: modules/framework/galasa-parent/**/build/reports/**/*.html
      #     retention-days: 7
      #     if-no-files-found: ignore

      - name: Upload framework artifacts
        uses: actions/upload-artifact@v4
        with:
          name: framework
          path: modules/framework/artifacts/dev/galasa
          retention-days: 7

  build-rest-api-documentation:
    name: Build REST API documentation using openapi2beans and gradle
    if: ${{ inputs.changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'
      
      - name: Install Swagger CLI
        working-directory: modules/framework
        run: |
          wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.41/swagger-codegen-cli-3.0.41.jar -O swagger-codegen-cli.jar
      
      - name: Generate Swagger docs
        working-directory: modules/framework
        run: |
          java -jar swagger-codegen-cli.jar generate -i galasa-parent/dev.galasa.framework.api.openapi/src/main/resources/openapi.yaml -l html2 -o docs/generated/galasaapi