#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Managers pull request build

on:
  workflow_call:
    inputs:
      changed:
        description: 'True if this module has been changed and should be rebuilt'
        required: true
        type: boolean

jobs:

  log-unchanged:
    name: Managers is unchanged
    if: ${{ !inputs.changed }}
    runs-on: ubuntu-latest

    steps:
      - name: Log this module is unchanged
        run: |
          echo "The managers module is unchanged"

  build-managers:
    name: Build Managers source code and Docker image
    if: ${{ inputs.changed }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'
        
      - name: Print githash
        run: |
          echo $GITHUB_SHA > ./managers.githash

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
          cache-disabled: true

      - name: Download wrapping artifacts
        uses: actions/download-artifact@v4
        with:
          name: wrapping
          path: modules/wrapping/dev/galasa
          run-id: 11364581065
  
      - name: Download gradle artifacts
        uses: actions/download-artifact@v4
        with:
          name: gradle
          path: modules/artifacts/dev/galasa
          run-id: 11364581065

      - name: Download maven artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven
          path: modules/artifacts/dev/galasa
          run-id: 11364581065

      - name: Download framework artifacts
        uses: actions/download-artifact@v4
        with:
          name: framework
          path: modules/artifacts/dev/galasa
          run-id: 11364581065
      
      - name: Build Managers source code
        working-directory: modules/managers
        run: |
          set -o pipefail
          gradle -b galasa-managers-parent/build.gradle check publish --info \
          --no-daemon --console plain \
          -Dorg.gradle.jvmargs=-Xmx4096M \
          -PsourceMaven=${{ github.workspace }}/modules/artifacts \
          -PcentralMaven=https://repo.maven.apache.org/maven2/ \
          -PtargetMaven=${{ github.workspace }}/modules/managers/artifacts 2>&1 | tee build.log

      - name: Upload Gradle Build Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: managers-gradle-build-log
          path: modules/managers/build.log
          retention-days: 7
            
      - name: Upload Jacoco Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: managers-jacoco-report
          path: modules/managers/galasa-managers-parent/**/**/build/reports/**/*.html
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload managers artifacts
        uses: actions/upload-artifact@v4
        with:
          name: managers
          path: modules/managers/artifacts/dev/galasa
          retention-days: 7