#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Pull Request Build

on:
  pull_request:
    branches: [main]

jobs:

  # Get modules that were changed as part of this Pull Request,
  # set that as an output of this job to be passed to the next job. 
  get-changed-modules:
    name: Get the modules changed in this Pull Request
    runs-on: ubuntu-latest

    outputs:
      buildutils_changed: ${{ steps.get-changed-modules.outputs.BUILDUTILS_CHANGED }}
      wrapping_changed: ${{ steps.get-changed-modules.outputs.WRAPPING_CHANGED }}
      gradle_changed: ${{ steps.get-changed-modules.outputs.GRADLE_CHANGED }}
      maven_changed: ${{ steps.get-changed-modules.outputs.MAVEN_CHANGED }}
      framework_changed: ${{ steps.get-changed-modules.outputs.FRAMEWORK_CHANGED }}
      extensions_changed: ${{ steps.get-changed-modules.outputs.EXTENSIONS_CHANGED }}
      managers_changed: ${{ steps.get-changed-modules.outputs.MANAGERS_CHANGED }}
      obr_changed: ${{ steps.get-changed-modules.outputs.OBR_CHANGED }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get the modules changed in this Pull Request
        id: get-changed-modules
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./tools/get-changed-modules-pull-request.sh --pr-number ${{ github.event.number }}

  # Call the build orchestrator in Pull Request mode.
  build-orchestrator:
    name: Call the Build Orchestrator
    needs: [get-changed-modules]
    uses: ./.github/workflows/build-orchestrator.yaml
    secrets: inherit
    with:
      pull_request_build: ${{ true }}
      buildutils_changed: ${{ needs.get-changed-modules.outputs.buildutils_changed }}
      wrapping_changed: ${{ needs.get-changed-modules.outputs.wrapping_changed }}
      gradle_changed: ${{ needs.get-changed-modules.outputs.gradle_changed }}
      maven_changed: ${{ needs.get-changed-modules.outputs.maven_changed }}
      framework_changed: ${{ needs.get-changed-modules.outputs.framework_changed }}
      extensions_changed: ${{ needs.get-changed-modules.outputs.extensions_changed }}
      managers_changed: ${{ needs.get-changed-modules.outputs.managers_changed }}
      obr_changed: ${{ needs.get-changed-modules.outputs.obr_changed }}