#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Pull Requests

on:
  pull_request:
    branches: [main]

env:
  # These environment variables are set to false as default,
  # but are updated by the first job below.
  BUILDUTILS_CHANGED: 'false'
  WRAPPING_CHANGED: 'false'
  GRADLE_CHANGED: 'false'
  MAVEN_CHANGED: 'true'
  FRAMEWORK_CHANGED: 'false'
  EXTENSIONS_CHANGED: 'false'
  MANAGERS_CHANGED: 'true'
  OBR_CHANGED: 'false'

jobs:

  # TODO: Script needs to output environment variables of 'true' or 'false' for modules changed
  # get-changed-modules:
  #   name: Get the modules changed in this Pull Request
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Get the modules changed in this Pull Request
  #       env:
  #         GH_TOKEN: ${{ github.token }}
  #       run: |
  #         ./tools/get-changed-modules.sh --pr-number ${{ github.event.number }}

  #     - name: Access the output from the script
  #       run: |
  #         echo "The script output is: ${{ env.FIRST_CHANGED_MODULE }}"

  # Environment variables can't be passed directly to reusable workflows,
  # so they need to be exposed as outputs of this job to be used below.
  expose-environment-variables:
    name: Expose environment variables to pass to build orchestrator
    runs-on: ubuntu-latest

    outputs:
      buildutils_changed: ${{ env.BUILDUTILS_CHANGED }}
      wrapping_changed: ${{ env.WRAPPING_CHANGED }}
      gradle_changed: ${{ env.GRADLE_CHANGED }}
      maven_changed: ${{ env.MAVEN_CHANGED }}
      framework_changed: ${{ env.FRAMEWORK_CHANGED }}
      extensions_changed: ${{ env.EXTENSIONS_CHANGED }}
      managers_changed: ${{ env.MANAGERS_CHANGED }}
      obr_changed: ${{ env.OBR_CHANGED }}

    steps:
      - run: echo "Exposing environment variables"

  # Call the build orchestrator in Pull Request mode.
  build-orchestrator:
    name: Call the Build Orchestrator
    needs: [expose-environment-variables]
    uses: ./.github/workflows/build-orchestrator.yaml
    secrets: inherit
    with:
      pull_request_build: ${{ true }}
      buildutils_changed: ${{ needs.expose-environment-variables.outputs.buildutils_changed }}
      wrapping_changed: ${{ needs.expose-environment-variables.outputs.wrapping_changed }}
      gradle_changed: ${{ needs.expose-environment-variables.outputs.gradle_changed }}
      maven_changed: ${{ needs.expose-environment-variables.outputs.maven_changed }}
      framework_changed: ${{ needs.expose-environment-variables.outputs.framework_changed }}
      extensions_changed: ${{ needs.expose-environment-variables.outputs.extensions_changed }}
      managers_changed: ${{ needs.expose-environment-variables.outputs.managers_changed }}
      obr_changed: ${{ needs.expose-environment-variables.outputs.obr_changed }}
      