#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Main Build Orchestrator

on:
  push:
    branches: [main]

jobs:

  # Get modules that were changed as part of this Push,
  # set that as an output of this job to be passed to the next job. 
  get-changed-modules:
    name: Get the modules changed in this Push
    runs-on: ubuntu-latest

    outputs:
      buildutils_changed: ${{ steps.get-changed-modules.outputs.BUILDUTILS_CHANGED }}
      wrapping_changed: ${{ steps.get-changed-modules.outputs.WRAPPING_CHANGED }}
      gradle_changed: ${{ steps.get-changed-modules.outputs.GRADLE_CHANGED }}
      maven_changed: ${{ steps.get-changed-modules.outputs.MAVEN_CHANGED }}
      framework_changed: ${{ steps.get-changed-modules.outputs.FRAMEWORK_CHANGED }}
      extensions_changed: ${{ steps.get-changed-modules.outputs.EXTENSIONS_CHANGED }}
      managers_changed: ${{ steps.get-changed-modules.outputs.MANAGERS_CHANGED }}
      obr_changed: ${{ steps.get-changed-modules.outputs.OBR_CHANGED }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log base and head commits of this Push event
        run : |
          echo "Base commit: ${{ github.event.before }}"
          echo "Head commit: ${{ github.sha }}"

      - name: Get the modules changed in this Push
        id: get-changed-modules
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./tools/get-changed-modules-push.sh --repo ${{ github.repository }} --base ${{ github.event.before }} --head ${{ github.sha }}

  build-buildutils:
    # if: ${{ !inputs.pull_request_build }}
    name: Build the 'buildutils' module
    needs: [get-changed-modules]
    uses: ./.github/workflows/buildutils.yaml
    secrets: inherit
    with:
      changed: ${{ needs.get-changed-modules.outputs.buildutils_changed }}

  build-wrapping:
    # if: ${{ !inputs.pull_request_build }}
    name: Build the 'wrapping' module
    needs: [get-changed-modules]
    uses: ./.github/workflows/wrapping.yaml
    secrets: inherit
    with:
      changed: ${{ needs.get-changed-modules.outputs.wrapping_changed }}

  build-gradle:
    # if: ${{ !inputs.pull_request_build }}
    name: Build the 'gradle' module
    needs: [get-changed-modules]
    uses: ./.github/workflows/gradle.yaml
    secrets: inherit
    with:
      changed: ${{ needs.get-changed-modules.outputs.gradle_changed }}

  build-maven:
    # if: ${{ !inputs.pull_request_build }}
    name: Build the 'maven' module
    needs: [get-changed-modules, build-gradle]
    uses: ./.github/workflows/maven.yaml
    secrets: inherit
    with:
      changed: ${{ needs.get-changed-modules.outputs.maven_changed }}

  build-framework:
    # if: ${{ !inputs.pull_request_build }}
    name: Build the 'framework' module
    needs: [get-changed-modules, build-buildutils, build-wrapping, build-maven]
    uses: ./.github/workflows/framework.yaml
    secrets: inherit
    with:
      changed: ${{ needs.get-changed-modules.outputs.framework_changed }}

  build-extensions:
    # if: ${{ !inputs.pull_request_build }}
    name: Build the 'extensions' module
    needs: [get-changed-modules, build-framework]
    uses: ./.github/workflows/extensions.yaml
    secrets: inherit
    with:
      changed: ${{ needs.get-changed-modules.outputs.extensions_changed }}

  build-managers:
    # if: ${{ !inputs.pull_request_build }}
    name: Build the 'managers' module
    needs: [get-changed-modules, build-framework]
    uses: ./.github/workflows/managers.yaml
    secrets: inherit
    with:
      changed: ${{ needs.get-changed-modules.outputs.managers_changed }}

  build-obr:
    # if: ${{ !inputs.pull_request_build }}
    name: Build the 'obr' module
    needs: [get-changed-modules, build-extensions, build-managers]
    uses: ./.github/workflows/obr.yaml
    secrets: inherit
    with:
      changed: ${{ needs.get-changed-modules.outputs.obr_changed }}
