#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Main Build Orchestrator

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  set-build-properties:
    # Use the version.properties file to source the galasa-version output variable.
    # This variable can be referenced by other jobs in this flow using 
    # ${{ needs.set-build-properties.outputs.galasa-version }}
    runs-on: ubuntu-latest
    outputs:
      galasa-version: ${{ steps.set-build-properties.outputs.GALASA_VERSION }}
    steps:
      - id: checkout-code
        uses: actions/checkout@v4 
        with:
          sparse-checkout: |
            build.properties
          sparse-checkout-cone-mode: false

      - id: set-build-properties
        run: |
          cat build.properties | grep "=" >> $GITHUB_OUTPUT

  check-required-secrets-configured:
    name: Check required secrets configured
    uses: ./.github/workflows/check-required-secrets-configured.yaml
    with:
      check_write_github_packages_username: 'true'
      check_write_github_packages_token: 'true'
      check_gpg_key: 'true'
      check_gpg_keyid: 'true'
      check_gpg_passphrase: 'true'
    secrets:
      WRITE_GITHUB_PACKAGES_TOKEN: ${{ secrets.WRITE_GITHUB_PACKAGES_TOKEN }}
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_KEYID: ${{ secrets.GPG_KEYID }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  build-platform:
    name: Build the 'platform' module
    needs: [check-required-secrets-configured]
    uses: ./.github/workflows/platform.yaml
    secrets: inherit

  build-buildutils:
    name: Build the 'buildutils' module
    needs: [check-required-secrets-configured]
    uses: ./.github/workflows/buildutils.yaml
    secrets: inherit

  build-wrapping:
    name: Build the 'wrapping' module
    needs: [build-platform]
    uses: ./.github/workflows/wrapping.yaml
    secrets: inherit

  build-gradle:
    name: Build the 'gradle' module
    needs: [build-platform]
    uses: ./.github/workflows/gradle.yaml
    secrets: inherit

  build-maven:
    name: Build the 'maven' module
    needs: [build-gradle]
    uses: ./.github/workflows/maven.yaml
    secrets: inherit

  build-framework:
    name: Build the 'framework' module
    needs: [build-buildutils, build-wrapping, build-maven]
    uses: ./.github/workflows/framework.yaml
    secrets: inherit

  build-extensions:
    name: Build the 'extensions' module
    needs: [build-framework]
    uses: ./.github/workflows/extensions.yaml
    secrets: inherit

  build-managers:
    name: Build the 'managers' module
    needs: [build-framework]
    uses: ./.github/workflows/managers.yaml
    secrets: inherit

  build-obr:
    name: Build the 'obr' module
    needs: [build-extensions, build-managers, set-build-properties]
    uses: ./.github/workflows/obr.yaml
    secrets: inherit
    with:
      galasa-version: "${{ needs.set-build-properties.outputs.galasa-version }}"

  # The IVTs are built after the OBR as they require the galasa-bom to get dependencies.
  build-ivts:
    name: Build the 'ivts' module
    needs: [build-obr]
    uses: ./.github/workflows/ivts.yaml
    secrets: inherit

  download-artifacts-for-codeql:
    name: Download artifacts for Advanced CodeQL Java scan
    runs-on: ubuntu-latest
    needs: [build-ivts]

    steps:
      - name: Download Platform from this Workflow Run
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: platform
          path: /home/runner/.m2/repository

      - name: Download Wrapping from this Workflow Run
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: wrapping
          path: /home/runner/.m2/repository

      - name: Download Gradle from this Workflow Run
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: gradle
          path: /home/runner/.m2/repository

      - name: Download Maven from this Workflow Run
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: maven
          path: /home/runner/.m2/repository

      - name: Download Framework from this Workflow Run
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: framework
          path: /home/runner/.m2/repository

      - name: Download Extensions from this Workflow Run
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: extensions
          path: /home/runner/.m2/repository

      - name: Download Managers from this Workflow Run
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: managers
          path: /home/runner/.m2/repository

      - name: Download OBR from this Workflow Run
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: obr
          path: /home/runner/.m2/repository

      - name: Download IVTs from this Workflow Run
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: ivts
          path: /home/runner/.m2/repository

      - name: Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-artifacts
          path: /home/runner/.m2/repository/dev/galasa

  codeql-java:
    name: CodeQL scans the Java code
    needs: [download-artifacts-for-codeql]
    uses: ./.github/workflows/codeql-java.yml
    secrets: inherit
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

  codeql-go:
    name: CodeQL scans the Golang code
    needs: [download-artifacts-for-codeql]
    uses: ./.github/workflows/codeql-go.yml
    secrets: inherit
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

  build-cli:
    name: Build the 'cli' module
    needs: [build-obr]
    uses: ./.github/workflows/cli.yaml
    secrets: inherit

  build-docs:
    name: Build the Galasa documentation 
    needs: [build-cli]
    uses: ./.github/workflows/docs.yaml
    secrets: inherit