#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Wrapping build

on:
  workflow_call:

env:
  BRANCH: ${{ github.ref_name }}

jobs:
  log-github-ref:
    name: Log the GitHub ref this workflow is running on (Branch or tag that received dispatch)
    runs-on: ubuntu-latest
    
    steps:
      - name: Log GitHub ref of workflow
        run: |
          echo "This workflow is running on GitHub ref ${{ env.BRANCH }}"

  build-wrapping:
    name: Build Wrapping source code and Docker image for development Maven registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'
          # cache: 'maven'

      # The githash is added to the development Maven registry to show what commit level it contains
      - name: Print githash
        run: |
          echo $GITHUB_SHA > ./wrapping.githash

      # Copy secrets into files to use in workflow
      - name: Make secrets directory
        run: |
          mkdir /home/runner/work/secrets
      - name: Copy settings.xml
        env:
          MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
        run: |
          echo $MAVEN_SETTINGS_XML > /home/runner/work/secrets/settings.xml
      - name: Copy GPG passphrase
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo $GPG_PASSPHRASE > /home/runner/work/secrets/passphrase.file
      - name: Copy GPG key
        env:
          GPG_KEY_BASE64: ${{ secrets.GPG_KEY }}
        run: |
          echo $GPG_KEY_BASE64 |  base64 --decode > /home/runner/work/secrets/galasa.gpg
          
      # Set up Maven GPG directory
      - name: Make GPG home directory
        run: |
          mkdir /home/runner/work/gpg
      
      - name: Change directory permissions
        run: |
          chmod '700' /home/runner/work/gpg

      - name: Import GPG
        run: |
          gpg --homedir /home/runner/work/gpg --pinentry-mode loopback --passphrase-file /home/runner/work/secrets/passphrase.file --import /home/runner/work/secrets/galasa.gpg
      
      - name: Copy custom settings.xml
        run: |
          cp /home/runner/work/secrets/settings.xml /home/runner/work/gpg/settings.xml

      # - name: Restore cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ github.workspace }}/modules/artefacts
      #     key: cache-key-${{ env.BRANCH }}
      #     restore-keys: |
      #       cache-key-

      - name: Build Wrapping source code
        working-directory: modules/wrapping
        run : |
          set -o pipefail
          mvn deploy -X \
          -Dgalasa.source.repo=file:${{ github.workspace }}/modules/artefacts \
          -Dgalasa.central.repo=https://repo.maven.apache.org/maven2/ \
          -Dgalasa.release.repo=file:${{ github.workspace }}/modules/artefacts \
          -Dgalasa.jacocoEnabled=true \
          -Dgalasa.isRelease=true \
          --batch-mode --errors --fail-at-end \
          --settings /home/runner/work/gpg/settings.xml 2>&1 | tee build.log

      - name: Upload Maven Build Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wrapping-maven-build-log
          path: modules/wrapping/build.log

      # - name: Save cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ github.workspace }}/modules/artefacts
      #     key: cache-key-${{ env.BRANCH }}

      - name: Show contents of cache directory
        run : |
          ls -R ${{ github.workspace }}/modules/artefacts || true